### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by stickylabdev** [BazingoW/Map-Editor-2D-for-Unity#3]
The type or namespace name `UnityEditor' could not be found. Are you missing an assembly reference?

**Comment by DonHaul** [comment]
Hi, could you tell me what were the steps to reproduce the issue please.

I just tested in Unity5.5.0f3 and it works

**Comment by stickylabdev** [comment]
same versions .. i fixed that by moving the script to editor folder maybe ( if i m not forget )

**Comment by DonHaul** [comment]
Nice, if you download just import the unitypackage from the releases page I think the scripts will go directly to the Editor folder
